export const restArray = [
  {
    id: 0,
    title: "Пицца плюс",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "pizza-plus.jpg",
  },
  {
    id: 0,
    title: "Тануки",
    time: 50,
    rating: 4.4,
    price: 900,
    type: "Пицца",
    image: "tanuki.jpg",
  },
  {
    id: 0,
    title: "FoodBand",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "FoodBand.jpg",
  },
  {
    id: 0,
    title: "Жадина-пицца",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "Жадина-пицца.jpg",
  },
  {
    id: 0,
    title: "Точка еды",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "Точка еды.jpg",
  },
  {
    id: 0,
    title: "PizzaBurger",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "PizzaBurger.jpg",
  },
];
